language: node_js
node_js:
- "5.7.0"
sudo: false
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: ed11d72d-8ffb-43a4-9495-366025ab4e2f
  app:
    master: kyper-devshare
