language: node_js

node_js:
  - "6"

cache:
  bundler: true
  directories:
    - node_modules # NPM packages

install:
  - npm set progress=false
  - npm install -g firebase-tools
  - npm install

script:
  - npm run lint:fix
  - npm run test
  - npm run build:prod
  - npm run deploy

after_success:
  - npm run codecov

notifications:
  email:
    on_failure: change
    on_success: change
