sudo: false

language: node_js

node_js:
  - 6.10.0

cache:
  directories:
    - node_modules

install:
  - npm set progress=false
  - npm install # install project dependencies

branches:
  only:
    - master
    - prod
    - stage

script:
  - npm run config
  - npm run lint:fix
  - npm run test
  - npm run build:prod

after_success:
  - npm install --prefix ./functions # install functions dependencies
  - npm i -g firebase-ci # install firebase-ci
  - firebase-ci deploy

notifications:
  email:
    on_failure: change
    on_success: change
